* Leetcode Emacs Layer

This layer adds the functionality to use leetcode from within Emacs. This layer uses the wonderful package available at [[https://github.com/ginqi7/leetcode-emacs][leetcode-emacs]]. The package depends on the following, which in turn makes the layer depend on the following:

** Dependencies

1. [[https://github.com/skygragon/leetcode-cli][leetcode-cli]]

This node package is required and needs to be available in path for the layer to work. You can very easily also add plugins. There are also prebuilt binaries available [[https://github.com/skygragon/leetcode-cli/releases][here]].

2. Emacs packages ctable and names

The layer uses the ctable package to display eveything in a table and uses the names package to excapsulate everything in namespaces since ELisp doesn't directly support namespaces.

** Installation

To install the layer, clone it into the private repo:

#+begin_src bash
git clone https://github.com/anmoljagetia/leetcode-emacs-layer.git ~/.emacs.d/private/myleetcode
#+end_src

Once the layer has been cloned, add it to the =dotspacemacs-configuration-layers= like the following:

#+begin_src elisp
  dotspacemacs-configuration-layers
    '(
      myleetcode
      .
      .
      .
      
#+end_src
